### ISSUE TITLE
Cannot install due to slevomat/consistence dependency

### ISSUE THREAD

**Issue by adaamz** [spell-checker/spell-checker#2]
Hi,
I would like to try this package, but it looks like slevomat/consistence is removed or private repository.

**Comment by paranoiq** [comment]
Hi,
mea culpa. fixed in v0.3.4

btw. **any feed back is welcome**. readme is now a little bit outdated, but i hope you can figure out configuration from config in spell-check project itself and from `--help`. if you have any questinons, contact me at `Pehápkáři` slack

public release/announcement of spell-checker will be with v0.4... maybe in two months
